---
title: "week3"
author: "Carmen Pfoster"
date: '2022-05-06'
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)

caro <- read_delim("caro60.txt",",")
```

```{r}
caro %>%
  ggplot(aes(E, N))  +
  geom_path() +
  geom_point() +
  coord_fixed() +
  theme(legend.position = "bottom")

caro <- caro %>%
  mutate(
    nMinus3 = sqrt((lag(E,3)-E)^2+(lag(N,3)-N)^2),   # distance to pos - 3 minutes
    nMinus2 = sqrt((lag(E,2)-E)^2+(lag(N,2)-N)^2),   # distance to pos -2 minutes
    nMinus1 = sqrt((lag(E,1)-E)^2+(lag(N,1)-N)^2),   # distance to pos -1 minutes
    nPlus1  = sqrt((E-lead(E,1))^2+(N-lead(N,1))^2), # distance to pos +1 mintues
    nPlus2  = sqrt((E-lead(E,2))^2+(N-lead(N,2))^2),  # distance to pos +2 minutes
    nPlus3  = sqrt((E-lead(E,3))^2+(N-lead(N,3))^2))  # distance to pos +3

caro <- caro %>%
  rowwise() %>%
  mutate(
    stepMean = mean(c(nMinus3, nMinus2, nMinus1, nPlus1, nPlus2, nPlus3))
  ) %>%
  ungroup()

caro
```

```{r}
summary(caro$stepMean)
ggplot()+
  geom_boxplot(data=caro, aes(y=stepMean))
```

```{r}
caro <- caro %>% 
  ungroup() %>%
  mutate(static = stepMean < mean(stepMean, na.rm = TRUE))


caro_filter <- caro %>%
  filter(!static)

caro_filter%>%
  ggplot(aes(E, N))  +
  geom_path() +
  geom_point() +
  coord_fixed() +
  theme(legend.position = "bottom")
```

```{r}
caro%>%
  ggplot(aes(E, N))  +
  geom_path() +
  geom_point(aes(color=static)) +
  coord_equal()+
  ggtitle("Visualizing calculated rest points")
```

```{r}
rle_id <- function(vec){
  x <- rle(vec)$lengths
  as.factor(rep(seq_along(x), times=x))
  }
```

```{r}
caro <- caro %>%
  mutate(segment_id = rle_id(static))

caro
```

```{r}
caro_moving <- caro %>% 
  filter(caro$static == FALSE)

caro_moving%>%
  ggplot(aes(E, N, color=segment_id))  +
  geom_path() +
  geom_point() +
  coord_equal()+
  ggtitle("Moving segments coloured by segment ID (uncleaned)")
```

```{r}
caro_moving <- caro_moving %>% 
  group_by(segment_id) %>% 
  mutate(count= n()) %>% 
  ungroup() %>% 
  filter(count>5)

caro_moving%>%
  ggplot(aes(E, N, color=segment_id))  +
  geom_path() +
  geom_point() +
  coord_equal()+
  ggtitle("Moving segments coloured by segment ID (removed segments <5)")
```

```{r}
pedestrians <- read_delim("pedestrian.txt",",")
```

```{r}
ggplot(pedestrians, aes(E, N, color=TrajID))  +
  geom_path() +
  geom_point() +
  coord_equal()+
  facet_wrap(~TrajID)+
  labs(title="visual comparison of the 6 trajectories", subtitle="Each subplot highlights a trajectory")
```

```{r}
install.packages("SimilarityMeasures")
library(SimilarityMeasures)

pedestrians <- select(pedestrians, -DatetimeUTC)

traj1 <- pedestrians %>% 
  filter(TrajID ==1) %>% 
  as.matrix()
traj2 <- pedestrians %>% 
  filter(TrajID ==2) %>% 
  as.matrix()
traj3 <- pedestrians %>% 
  filter(TrajID ==3) %>% 
  as.matrix()
traj4 <- pedestrians %>% 
  filter(TrajID ==4) %>% 
  as.matrix()
traj5 <- pedestrians %>% 
  filter(TrajID ==5) %>% 
  as.matrix()
traj6 <- pedestrians %>% 
  filter(TrajID ==6) %>% 
  as.matrix()

DTW1 = c(DTW(traj1, traj2, 4), 
         DTW(traj1, traj3, 4),
         DTW(traj1, traj4, 4),
         DTW(traj1, traj5, 4),
         DTW(traj1, traj6, 4))

EditDist1 = c(EditDist(traj1, traj2, 2), 
              EditDist(traj1, traj3, 2),
              EditDist(traj1, traj4, 2),
              EditDist(traj1, traj5, 2),
              EditDist(traj1, traj6, 2))

Frechet1 = c(Frechet(traj1, traj2), 
            Frechet(traj1, traj3),
            Frechet(traj1, traj4),
            Frechet(traj1, traj5),
            Frechet(traj1, traj6))

LCSS1 = c(LCSS(traj1, traj2, 2, 2), 
          LCSS(traj1, traj3, 2, 2),
          LCSS(traj1, traj4, 2, 2),
          LCSS(traj1, traj5, 2, 2),
          LCSS(traj1, traj6, 2, 2))


distances <- data.frame(
  traj= 2:6,
  DTW = DTW1,
  EditDist = EditDist1,
  Frechet = Frechet1,
  LCSS = LCSS1
)

library(tidyverse)

distances_long <- distances %>% 
  pivot_longer(-traj)
  

ggplot(distances_long, aes(x=traj, y=value, fill=as.factor(traj)))  +
  geom_col()+
  facet_wrap(~name, scales = "free_y")+
  theme(legend.position = "none")
  labs(title="visual comparison of the 6 trajectories", subtitle="Each subplot highlights a trajectory")
```

